### ISSUE TITLE
Can't get Train ID lookup working

### ISSUE THREAD

**Issue by Spiruel** [w-henderson/PyTrains#2]
Hi,

I'm having trouble getting Pytrains working for my purposes. Could you let me know if I'm doing anything wrong?

Firstly, I can't lookup Manchester Victoria (CRS is "MCV") station.

Secondly, I'm trying to lookup trains by their ID. For eg., https://live.rail-record.co.uk/train.php/?c=W37310&d=2022-05-19

`pytrains --id 1084753 LDS`

Gives me "invalid train ID"

Thanks

**Comment by w-henderson** [comment]
Sadly the API upon which PyTrains is built been deprecated (see [here](http://iris2.rail.co.uk/tiger/)) and the new API requires authentication (see [here](https://tiger.worldline.global/home)). I don't have time to completely migrate the system so unfortunately PyTrains will eventually stop working altogether. I'll mark the project as archived.
